const level1Strings = ["If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?", "Think of your favorite brand of cereal. On the count of three, say your answers out loud.", "How many speeding tickets do you think I've gotten in my life?", "Think of your favorite childhood TV show of all time. On the count of three, say it out loud.", "Rate your dancing skills on a scale of 1-10. On the count of three, say your answers out loud.", "Do you think I've ever been fired from a job? If so, what for?", "What's the first thing you noticed about me?", "Do you think I've ever checked an ex's phone for evidence?", "Do I seem like a coffee or tea person? Sweetened or unsweetened?", "What does my phone wallpaper tell you about me?", "Close your eyes. What color is my shirt?", "What do you think I'm most likely to splurge on?", "As a child, what do you think I wanted to be?", "What do you think is the hardest part of what I do for a living?", 
                        "What does my Instagram tell you about me?", "Do I seem like more of a creative or analytical type? Explain.", "Maintain eye contact for thirty seconds. What did you notice?", "What fast food restaurant do you think I'm most likely to drive through? What's my order?", "What subject do you think I thrived in at school? Did I fail any?", "Do I seem like a cat or dog person?", "What do my shoes tell you about me?", "How likely am I to go camping? How high maintenance is my set up?", "What is my body language telling you right now?", "What was your first impression of me?", "Do you think plants thrive or die in my care? Explain.", "Do I remind you of anyone?", "What character would I play in a movie?", "What reality show do you think I'm most likely to binge watch? Explain.", "Finish the sentence: Just by looking at you I'd think _________.", "Do you think I'm usually early, on time, or late to events? Explain.", "What compliment do you think I hear the most?", "Do I seem like someone who would get a name tattooed on myself? Why or why not?", "What do you think my go to karaoke song is?", "Do you think I intimidate others? Why or why not?", "Do you think I was popular in school? Explain.", "If MySpace were still a thing, what would my profile song be?", "What about me intrigues you?", "Do you thinkI fall in love easily? Why or why not?", "Who do you think my celebrity crush is?", "What about me is most strange or unfamiliar to you?", "Do I look kind? Explain.", "Do I seem like a morning person or a night owl? Why?"];
const level2Strings = ["What lesson took you the longest to unlearn?", "What is a dream you've let go of?", "Staring contest. First to blink must reveal a personal problem and ask your partner for advice on how they might handle it.", "What has been your earliest recollection of happiness?", "Are you missing anyone right now? Do you think they are missing you too?", "What would your younger self not believe about your life today?", "What's the most pain you've ever been in that wasn't physical?", "What question are you trying to answer most in your life right now?", "What is something you wouldn't want to change about yourself?", "What is a compliment you wish you received more frequently?", "Have you changed your mind about anything recently?", "Think of something you strongly dislike that most people love. On the count of three say it out loud.", "How are you, really?", "Press shuffle on your Spotify likes. Explain the first song that comes up.", "Finish the sentences: Strangers would describe me as _______. Only I know that I am _______.", "What are you more afraid of, failure or success? And why?", "What's been the best compliment a stranger has ever given you?", "What is your first love's name and the reason you fell in love with him/her?", "What do you think my defining characteristic is?",
                        "What's your father's name? And tell me one thing about him.", "Do you think the image you have of yourself matches the image people see you as?", "Ask a question you'd be too afraid to ask. Something you wouldn't dare ask.", "If you could have it your way: who would you be with? Where would you be? & What would you be doing?", "Are you lying to yourself about anything?", "Show the first photo in your camera roll. Explain.", "What's been your happiest memory this past year?", "What do you crave more of?", "How can you become a better person?", "When was the last time you surprised yourself?", "What are you still trying to prove to yourself?", "Has a stranger ever changed your life?", "What is the most unexplainable thing that's ever happened to you?", "If you could get to know someone in your life on a deeper level, who would it be and why?", "How would you describe the feeling of being in love in one word?", "If you have, when was the moment you realized you weren't invincible?", "Describe your perfect day.", "What title would you give this chapter in your life?", "When you're asked how are you, how often do you answer truthfully?", "What part of your life works? What part of your life hurts?", "Is there a feeling you miss?", "What's your mother's name? And the most beautiful thing about her?", "Have you ever told someone I love you but didn't mean it? If so, why?", "What is the last thing you lied to your mother about?"];
const level3Strings = ["What do you think my weakness is?", "When this game is over, what will you remember about me?", "When in this game did you feel most connected to me?", "Swap a song suggestion your partner may enjoy.", "What answer of mine made you light up?", "Scroll through each other's Instagrams. Find the picture you feel best represents your partner's essence and comment why you chose that image.", "What do you recommend I let go of, if anything?", "Why do you think we met?", "If we were in a band, what would our name be?", "What parts of yourself do you see in me?", "Dare your partner to do something outside of their comfort zone in the next week.", "What has this conversation taught you about yourself?", "Think of a goal for this year. Exchange. Hold each other accountable.", "What question were you most afraid to answer?", "Play a round of rock, paper, scissors. Winner can ask their partner anything. Loser must answer.", "What can I help you with?", "How does one earn your vulnerability? Have I earned it? How can I earn more?", "Share something you're most grateful for in this current moment.", "How would you describe me to a stranger?", "If you could prescribe me one thing to do for the rest of this month, what would it be and why?", "Give your partner a compliment you don't think they hear enough.", "What would make you feel closer to me?", "Do you believe everyone has a calling? If so, do you think I've found mine?", "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?", "What do you think my superpower is?", "What am I most qualified to give advice about?", "What do you think I should know about myself that perhaps I'm unaware of?",
                        "What do you admire most about me?", "Based on what you know about me, do you have any TV show/movie recommendations?", "What can we create together?", "How do our personalities complement each other?", "Each player write a message to the other. Fold and exchange. Open only once you two have parted.", "What do I need to hear right now?", "What do you think I fear the most?", "What do you think our most important similarity is?", "In one word, describe how you feel right now.", "What about me most surprised you?", "What would be the perfect gift for me?", "In one word, how would you describe our conversation?", "What about me is hardest for you to understand?", "What is a lesson you will take away from our conversation?", "Based on what you learned about me, what book would you recommend I read?", ""];

function getRandomString(strings) {
  const randomIndex = Math.floor(Math.random() * strings.length);
  return strings[randomIndex];
}

function showRandomString(level, levelNum) {
  const randomString = getRandomString(level);
  document.body.innerHTML = `
    <div class="container">
      <h1>Level ${levelNum}</h1>
      <p>${randomString}</p>
      <button id="backBtn">Back</button>
    </div>
  `;

  const backBtn = document.getElementById("backBtn");
  backBtn.addEventListener("click", () => {
    location.reload();
  });
}

document.getElementById("level1").addEventListener("click", () => {
  showRandomString(level1Strings, 1);
});

document.getElementById("level2").addEventListener("click", () => {
  showRandomString(level2Strings, 2);
});

document.getElementById("level3").addEventListener("click", () => {
  showRandomString(level3Strings, 3);
});
